export type ProductType = {
  id: number;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  image: string;
  //pack?: string;
  description?: string;
  features?: string[];
  sku?: string;
  rating?: number;
  reviewCount?: number;
  inStock?: boolean;
  relatedProducts?: number[];
  slug?: string;
  categories?: string[];
  galleryImages?: string[];
  tags?: string[];
};